const {
  SPENDIT_NODE_ENV,
  SPENDIT_DEV_PORT,
  SPENDIT_DEV_DATABASE_URL
} = process.env;

export default {
  SPENDIT_NODE_ENV: SPENDIT_NODE_ENV, 
  PORT: SPENDIT_DEV_PORT, 
  SPENDIT_DATABASE_URL: SPENDIT_DEV_DATABASE_URL 
};
