const {
  SPENDIT_NODE_ENV,
  SPENDIT_TEST_PORT,
  SPENDIT_TEST_DATABASE_URL
} = process.env;

export default {
  SPENDIT_NODE_ENV,
  PORT: SPENDIT_TEST_PORT,
  SPENDIT_DATABASE_URL: SPENDIT_TEST_DATABASE_URL
};
